Neoslive:
  Hybridsearch:
    Firebase:
      endpoint: 'https://phlu-f98dd.firebaseio.com'
      token: '4h2MfKKtGkpsBCg0tcxoRzvVnmiFapCv6L3UqfWZ'
      path: '/search'
    Filter:
      GrantParentNodeTypeFilter: '[instanceof TYPO3.Neos:Document]'
      ParentNodeTypeFilter: '[instanceof TYPO3.Neos:Content]'
      NodeTypeFilter: '[instanceof TYPO3.Neos:Node]'
Flowpack:
  JobQueue:
    Common:
      queues:
        'neoslive-hybridsearch-queue':
          className: 'Neoslive\Hybridsearch\Queue\SearchIndexJob'
          executeIsolated: true
          options:
            defaultTimeout: 500000
          releaseOptions:
            priority: 512
            delay: 120