TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Neoslive.Hybridsearch': TRUE
Neoslive:
  Hybridsearch:
    Realtime: false
    Firebase:
      endpoint: 'https://phlu-f98dd.firebaseio.com'
      token: '4h2MfKKtGkpsBCg0tcxoRzvVnmiFapCv6L3UqfWZ'
    Filter:
      GrantParentNodeTypeFilter: '[instanceof TYPO3.Neos:Document]'
      ParentNodeTypeFilter: '[instanceof TYPO3.Neos:Content]'
      NodeTypeFilter: '[instanceof Neoslive.Hybridsearch:Content]'
    TypoScriptPaths:
      'page':
        PHLU.Corporate: 'neosliveHybridsearch'
      'breadcrumb':
        PHLU.Corporate: 'neosliveHybridsearchBreadcrumb'



