Neoslive:
  Hybridsearch:
    Firebase:
      endpoint: 'https://phlu-f98dd.firebaseio.com'
      token: '4h2MfKKtGkpsBCg0tcxoRzvVnmiFapCv6L3UqfWZ'
    Filter:
      GrantParentNodeTypeFilter: '[instanceof TYPO3.Neos:Document]'
      ParentNodeTypeFilter: '[instanceof TYPO3.Neos:Content]'
      NodeTypeFilter: '[instanceof TYPO3.Neos:Node]'
TYPO3:
  Flow:
    http:
      baseUri: 'http://neos.phlu.ch'